title:              Jonathan Vosolo
email:              vosoloj@gmail.com
description:        Portfolio, Projects, knowledge base.
author:             Jonathan A. Vosolo
baseurl:            ""
url:                "https://jvosolo.github.io"

# Social Profiles
twitter_username:   vosoloj@gmail.com
github_username:    jvosolo
facebook_username:  jagevi@yahoo.com
instagram_username: jagevi@yahoo.com 
linkedin_username:  vosoloj@gmail.com

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
